### ISSUE TITLE
Error: Server terminated early with status 127

### ISSUE THREAD

**Issue by redi-kilicb** [trion-development/docker-ng-cli-e2e#14]
When I try to run ng e2e on my CI server's build (AWS CodeBuild, if it matters) using this Docker image, I get this error:

[01:59:25] I/file_manager - creating folder /codebuild/output/src043248699/src/node_modules/protractor/node_modules/webdriver-manager/selenium
--
136 | [01:59:25] I/config_source - curl -o/codebuild/output/src043248699/src/node_modules/protractor/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
137 | [01:59:25] I/downloader - curl -o/codebuild/output/src043248699/src/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_83.0.4103.39.zip https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
138 | [01:59:25] I/update - chromedriver: unzipping chromedriver_83.0.4103.39.zip
139 | [01:59:25] I/update - chromedriver: setting permissions to 0755 for /codebuild/output/src043248699/src/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_83.0.4103.39
140 | [01:59:25] I/launcher - Running 1 instances of WebDriver
141 | [01:59:25] I/direct - Using ChromeDriver directly...
142 | [01:59:25] E/launcher - Server terminated early with status 127
143 | [01:59:25] E/launcher - Error: Server terminated early with status 127
144 | at earlyTermination.catch.e (/codebuild/output/src043248699/src/node_modules/selenium-webdriver/remote/index.js:252:52)
145 | at process._tickCallback (internal/process/next_tick.js:68:7)
146 | From: Task: WebDriver.createSession()
147 | at Function.createSession (/codebuild/output/src043248699/src/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
148 | at Function.createSession (/codebuild/output/src043248699/src/node_modules/selenium-webdriver/chrome.js:761:15)
149 | at Direct.getNewDriver (/codebuild/output/src043248699/src/node_modules/protractor/built/driverProviders/direct.js:77:33)
150 | at Runner.createBrowser (/codebuild/output/src043248699/src/node_modules/protractor/built/runner.js:195:43)
151 | at q.then.then (/codebuild/output/src043248699/src/node_modules/protractor/built/runner.js:339:29)
152 | at _fulfilled (/codebuild/output/src043248699/src/node_modules/protractor/node_modules/q/q.js:834:54)
153 | at /codebuild/output/src043248699/src/node_modules/protractor/node_modules/q/q.js:863:30
154 | at Promise.promise.promiseDispatch (/codebuild/output/src043248699/src/node_modules/protractor/node_modules/q/q.js:796:13)
155 | at /codebuild/output/src043248699/src/node_modules/protractor/node_modules/q/q.js:556:49
156 | at runSingle (/codebuild/output/src043248699/src/node_modules/protractor/node_modules/q/q.js:137:13)
157 | [01:59:25] E/launcher - Process exited with error code 199

Is there anything in protractor.conf.js that we need to set differently to run it in Docker?

**Comment by everflux** [comment]
Could you show your `protractor.conf.js`?
