### ISSUE TITLE
e2e - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 84

### ISSUE THREAD

**Issue by gizbo** [trion-development/docker-ng-cli-e2e#15]
Hi,
    I'm getting the following error: 
E/direct - Error code: 135
[08:20:59] E/direct - Error message: Could not find chromedriver at /app/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_84.0.4147.30. Run 'webdriver-manager update' to download binaries.
[08:20:59] E/direct - Error: Could not find chromedriver at /app/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_84.0.4147.30. Run 'webdriver-manager update' to download binaries.

I notice you have instruction about locking the Chrome version but I might not be following it correctly cause it's giving me the following error:
Error: Could not find chromedriver at /app/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_84.0.4147.30. Run 'webdriver-manager update' to download binaries.

Ultimately I trying to had that to my gitlab-ci. This is what I have: 
test:e2e:
  stage: test
  extends: .tags
  image: trion/ng-cli-e2e:${CLI_VERSION}
  allow_failure: false
  script:
    - ./node_modules/protractor/node_modules/webdriver-manager/bin/webdriver-manager update --versions.chrome 84.0.4147.30
    - ng e2e --webdriver-update=false

Thanks,
Yves

**Comment by everflux** [comment]
Which version are you using (value of CLI_VERSION)?

You mention that your project is public, can you share the repo url?

**Comment by gizbo** [comment]
> Which version are you using (value of CLI_VERSION)?
> 
> You mention that your project is public, can you share the repo url?

sorry 9.1.7

**Comment by everflux** [comment]
You mention that your project is public, can you share the repo url?

**Comment by gizbo** [comment]
> You mention that your project is public, can you share the repo url?

Sorry it's not public

**Comment by everflux** [comment]
I see. Could you try the latest image and check, if your problem persists with it? (10.0.4)

**Comment by gizbo** [comment]
> I see. Could you try the latest image and check, if your problem persists with it? (10.0.4)

Worked with 10.0.4, so how can I lock it?

**Comment by jonasvoelcker** [comment]
Hello,

yesterday the 85 dropped into the stable channel. Unfortunately selenium immediately decided to switch, so from that time starting our CI is broken :/
https://www.ubuntuupdates.org/ppa/google_chrome?dist=stable
I've seen, that the stable-channel is part of the Docker build so could you please build a new tag? :)

Best Regards
Jonas

**Comment by everflux** [comment]
Jonas, thanks for bringing this to our attention. I will build a new :latest tag.

**Comment by jonasvoelcker** [comment]
Thanks for that, unfortunately it's still 84 :/
https://hub.docker.com/layers/trion/ng-cli-e2e/latest/images/sha256-c7d0ad17a30c9b64e865332afda9b13ddddc7ef31852d6c8d0da402db114bad5?context=explore

**Comment by jonasvoelcker** [comment]
Wonderful, now it perfectly works again :)

(Vielen Dank für die tollen Images, auf euch ist immer Verlass, offensichtlich sogar außerhalb der klassischen Arbeitszeiten!)

**Comment by everflux** [comment]
You are very welcome, thanks for the kind words. 
Sorry the build took so long. 

Please let us know if there is this kind of problem again.
