### ISSUE TITLE
update Chrome to newest version 87

### ISSUE THREAD

**Issue by NerdySoftPaw** [trion-development/docker-ng-cli-e2e#17]
we use the dockerimage in combination with playwright which uses the newest chrome drivers(Version 87.0.4280.20 )

it would be great if u can update the chrome install

**Comment by everflux** [comment]
Thanks for providing feedback in regards to the image.
Which version (tag) of the docker image are you using?

**Comment by NerdySoftPaw** [comment]
I've tested it with latest and 11.0.1

**Comment by everflux** [comment]
I will schedule a new build of the latest image, should fix this issue.

**Comment by NerdySoftPaw** [comment]
Thanks ;)

**Comment by NerdySoftPaw** [comment]
New image works Perfect. Issue can closed

**Comment by everflux** [comment]
Thank you for your feedback!
