### ISSUE TITLE
Difference to docker-ng-cli-karma?

### ISSUE THREAD

**Issue by loxy** [trion-development/docker-ng-cli-e2e#7]
Looking at the Dockerfile, I only see adding some JAVA stuff to the docker-ng-cli-karma image. I mean, why? What is the intense of docker-ng-cli-e2e?

**Comment by everflux** [comment]
You can use the e2e image to run protractor tests which require java for webdriver.

**Comment by loxy** [comment]
But why does it work to execute `ng e2e` in ng-cli-karma?

**Comment by everflux** [comment]
If you use the chromewebdriver directly instead of selenium, there is no java runtime requirement. In that case the ng-cli-karma image is sufficient.
